service: todo-serverless
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    MONGO_URI: ${env:MONGO_URI}


functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
